### ISSUE TITLE
Can not login in local docker deployment

### ISSUE THREAD

**Issue by zhouwubai** [refly-ai/refly#421]
**Describe the bug**
can not login in local docker deployment

**To Reproduce**
1. run the docker command `docker compose -f deploy/docker/docker-compose.yml up -d` in `reply` root directory. Running docker-compose gives me error
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
'include' does not match any of the regexes: '^x-'
```
2. Go to http://localhost:5700/
3. Click on `get started`
4. tried register/signup directly, google/github signup, neither works
5.  when trying to login, it gives me error (alert popup on the up-right corner: 
```
Oops, something went wrongCannot connect to the Refly server, please try again later.
```

**Desktop (please complete the following information):**
 - ubuntu
 - chrome

**Additional context**
I also tried to put a resend_api there

**Comment by pftom** [comment]
@zhouwubai We are currently optimizing the Docker local deployment to support local running without login and are working on the documentation. We expect to have this ready by this afternoon. Thank you! 🙏

**Comment by mrcfps** [comment]
Hi, @zhouwubai. You can now retry with following:

```bash
# Pull latest code
git pull origin main

# Pull our latest images
docker pull reflyai/refly-web:latest
docker pull reflyai/refly-api:latest

# Restart docker-compose
cd deploy/docker && docker-compose up -d
```

**Comment by WannaTen** [comment]
I got the same error even after updated the latest docker image. My environment is MacOS,  I could't open the refly_api service, I used docker exec netstat, got the result that there has no service listening on 5800:

/app/apps/api/dist # netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:44479        0.0.0.0:*               LISTEN      -
tcp        0      0 :::5801                 :::*                    LISTEN      1/node

and finally got the same error:

Oops, something went wrong
Cannot connect to the Refly server, please try again later.

**Comment by mrcfps** [comment]
> I got the same error even after updated the latest docker image. My environment is MacOS, I could't open the refly_api service, I used docker exec netstat, got the result that there has no service listening on 5800:
> 
> /app/apps/api/dist # netstat -nltp Active Internet connections (only servers) Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name tcp 0 0 127.0.0.11:44479 0.0.0.0:* LISTEN - tcp 0 0 :::5801 :::* LISTEN 1/node
> 
> and finally got the same error:
> 
> Oops, something went wrong Cannot connect to the Refly server, please try again later.

@WannaTen Hi, I just updated the code and test it on a new machine. Could you bother trying again? 

1. Pull the latest main branch
2. Re-copy the `.env.example` (I made some changes, but the required envs should keep the same)
3. Re-run `docker compose up -d`

**Comment by WannaTen** [comment]
> > I got the same error even after updated the latest docker image. My environment is MacOS, I could't open the refly_api service, I used docker exec netstat, got the result that there has no service listening on 5800:
> > /app/apps/api/dist # netstat -nltp Active Internet connections (only servers) Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name tcp 0 0 127.0.0.11:44479 0.0.0.0:* LISTEN - tcp 0 0 :::5801 :::* LISTEN 1/node
> > and finally got the same error:
> > Oops, something went wrong Cannot connect to the Refly server, please try again later.
> 
> [@WannaTen](https://github.com/WannaTen) Hi, I just updated the code and test it on a new machine. Could you bother trying again?
> 
> 1. Pull the latest main branch
> 2. Re-copy the `.env.example` (I made some changes, but the required envs should keep the same)
> 3. Re-run `docker compose up -d`

Thanks for your hard working! But what a pity that it still not work for me. maybe my environment gets something wrong, Dont worry for that, I would figure it out by myself and I will use my subscribed online service you guys provide. BTW,  Happy new year!!! 

---

Update: 
I restarted the refly_api container, and it works, I finally got the port 5800 opened. I think maybe there has some dependency among these backend service, the api service should start with some delay after all the other service started. 
And, when I signup a new user by email, the console return "strict-origin-when-cross-origin"，then I access localhost:5700, and cross origin error did not happen, as the requested api url is localhost:5800.   The latest problem is after I register an account,  I signin, but can not enter the free canvas page, still in the main page without a signed state.  A dead loop between signin and main page

**Comment by mrcfps** [comment]
Hi @WannaTen, thanks for your kind response.

> "I think maybe there has some dependency among these backend service, the api service should start with some delay after all the other service started."

Yes, exactly! I found out the timing for starting containers was quite the problem here, and I fixed in #430 by adding health checks to all middleware containers and ensure that the api service will only be started when dependent containers are ready (healthy). You can pull the latest main branch to see the difference.

> "A dead loop between signin and main page"

Consider clean the cookie for `localhost:5700` and refresh the page. If it still doesn't work, just let me know.

BTW, 新年快乐 🎆

**Comment by BryceWG** [comment]
我这边还是不行,排除了缓存干扰

**Comment by zhouwubai** [comment]
@mrcfps thanks. Everything works after pulling the latest code and setting REFLY_COOKIE_DOMAIN=localhost in .env

**Comment by yanmao2023** [comment]
I encountered the same error

**Comment by yanmao2023** [comment]
The latest problem is after I register an account, I signin, but can not enter the free canvas page, still in the main page without a signed state.

**Comment by yanmao2023** [comment]
> The latest problem is after I register an account, I signin, but can not enter the free canvas page, still in the main page without a signed state.

Sorry,When I set it at the final prompt, it works normally.“setting REFLY_COOKIE_DOMAIN=localhost in .env”

**Comment by woyin** [comment]
I found although I've use the latest docker image and set `REFLY_COOKIE_DOMAIN=localhost` and clean the cookie, I still cannot login in Safari 18.3 with my local deployed Refly. When I switched to Chrome, everything is OK.

<img width="1428" alt="Image" src="https://github.com/user-attachments/assets/cf4f53b9-0d1e-43fa-9544-596efac84af4" />

However, I can login in refly.ai website with Safari 18.3.
